import{a as T,S,i as l}from"./assets/vendor-550cebad.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="43066959-f9f55707df0fe34b818b99119",H="https://pixabay.com/api/";async function g(r,e,s){try{return(await T.get(H,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:s}})).data}catch(i){throw console.error("Error fetching images:",i),i}}const d=document.querySelector(".gallery"),L=new S(".gallery a",{captionsData:"alt"});L.refresh();function b(r){r.forEach(e=>{const s=`
      <li class="card">
        <a href="${e.largeImageURL}" class="link">
          <img src="${e.webformatURL}" alt="${e.tags}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${e.likes}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${e.views}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${e.comments}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${e.downloads}</p></li>
        </ul>
        </a>
        
      </li>
    `;d.insertAdjacentHTML("beforeend",s)}),L.refresh()}const h=document.querySelector(".scroll-to-top"),P=document.querySelector(".form"),y=document.querySelector(".search-input"),w=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");p();let a="",n=1;const u=15;P.addEventListener("submit",M);async function M(r){if(r.preventDefault(),a=y.value.trim(),n=1,d.innerHTML="",a===""){l.error({title:"Error",message:"Please enter a search term.",position:"center"}),c();return}E();try{const e=await g(a,n,u),s=e.totalHits;if(e.hits.length===0){d.innerHTML="",l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"}),c();return}else b(e.hits),y.value="",$();u*n>=s&&(c(),v())}catch(e){console.error("Error fetching images:",e),l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"center"})}finally{p()}}f.addEventListener("click",async()=>{try{f&&(n+=1);const r=await g(a,n,u),e=r.totalHits;b(r.hits),E(),u*n>=e&&(c(),v());const s=d.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"})}catch(r){console.error("Error fetching more images:",r),l.error({title:"Error",message:`Error fetching more images: ${r}`})}finally{p()}});function E(){w.classList.remove("hidden")}function p(){w.classList.add("hidden")}function $(){f.style.display="block"}function c(){f.style.display="none"}function v(){l.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results.",position:"center"})}window.addEventListener("scroll",()=>{document.body.scrollTop>30||document.documentElement.scrollTop>30?h.style.display="flex":h.style.display="none"});function C(){window.scrollTo({top:0,behavior:"smooth"})}h.addEventListener("click",C);
//# sourceMappingURL=commonHelpers.js.map
